stages:
  - build
  - deploy

build:
  image: node:16.13.0-slim
  stage: build
  only:
    - staging
    - production
  script:
    - echo "Building"
    - npm install
    - CI=false npm run-script build
  artifacts:
    paths:
      - build
    expire_in: 1 hour

deploy:
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only:
    - staging
    - production
  environment: $CI_COMMIT_BRANCH
  script:
    - echo "Deploying" 
    - echo $CI_COMMIT_REF_NAME
    - echo $CI_ENVIRONMENT_NAME
    # - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    # - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    # - mkdir ./build/app; cp ./build/index.html ./build/app
    # - mkdir ./build/admin; cp ./build/index.html ./build/admin
    # - mkdir ./build/disclaimer; cp ./build/index.html ./build/disclaimer
    # - aws s3 sync ./build/ $DEPLOY_URL --delete
    # - aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST --paths "/*"


