stages: 
  - build
  - deploy 

build: 
    image: node:16.13.0-slim
    stage: build
    script:
      - echo "Building"
      - npm install
      - CI=false npm run-script build
    artifacts:
      paths:
      - build
      expire_in: 1 hour

deploy_staging: 
  stage: deploy
  image: registry.gitlab.com/gitlab-org/cloud-deploy/aws-base:latest
  only: 
    - staging
  environment: staging
  variables: 
    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID_STAGING
    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY_STAGING
    DEPLOY_URL: $DEPLOY_URL_STAGING
  script:
    - echo "Deploying staging"
    - echo "Using $AWS_ACCESS_KEY_ID"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - echo "Using $AWS_SECRET_ACCESS_KEY"
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./build/ $DEPLOY_URL --delete

deploy_production:
  stage: deploy
  only:
    - production
  environment: production
  script:
    - echo "Deploying production"
    - echo "Using $AWS_ACCESS_KEY_ID"
    - aws configure set aws_access_key_id $AWS_ACCESS_KEY_ID
    - echo "Using $AWS_SECRET_ACCESS_KEY"
    - aws configure set aws_secret_access_key $AWS_SECRET_ACCESS_KEY
    - aws s3 sync ./build/ $DEPLOY_URL --delete
        

    
    




